- build.gradle
- src/main/java/sopt/org/umbbaServer/error/ApiResponse.java
- src/main/java/sopt/org/umbbaServer/error/ControllerExceptionAdvice.java
- src/main/java/sopt/org/umbbaServer/error/CustomException.java
- src/main/java/sopt/org/umbbaServer/error/ErrorType.java
- src/main/java/sopt/org/umbbaServer/error/SuccessType.java
- src/main/java/sopt/org/umbbaServer/util/AuditingTimeEntity.java
- src/main/java/sopt/org/umbbaServer/util/ServerProfileController.java
- src/main/java/sopt/org/umbbaServer/util/slack/SlackApi.java
- src/main/java/sopt/org/umbbaServer/util/slack/SlackTestController.java
생략
기본적인 에러 처리와 에러가 발생했을 때 Slack으로 메시지가 전송되는 기능 추가
> [FEAT] 에러 핸들링 + Slack 연동 기능 추가

- src/main/java/sopt/org/umbbaServer/config/SecurityConfig.java
closed #5
- CodeDeploy에서 deploy.sh를 실행할 때, /profile과 /health, /actuator/health를 호출하는데,
- 스프링 Security 설정파일의 AUTH_WHITELIST 배열에 등록해놓지 않았다보니 호출할 수 없는 오류 발생
- deploy.sh 파일에서 사용하는 API들 SecurityConfig AUTH_WHITELIST 배열에 등록 완료
> [FIX] deploy.sh 실행에서 사용하는 API들 SecurityConfig에서 풀어주기

- build.gradle
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboadringReceiveResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingInviteResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/respository/ParentchildRepository.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
- src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
- src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/UserInfoDto.java
- src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/response/UserLoginResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
- src/main/java/sopt/org/umbbaServer/global/common/dto/ApiResponse.java
- src/main/java/sopt/org/umbbaServer/global/config/jwt/JwtProvider.java
- src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
- src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
- src/main/resources/application.yaml
close #13 
- 초대하는 측과 받는 측의 온보딩 입력 API를 따로 분리
- 초대코드 발급
- 부모자식 관계 케이스 4가지 중 분류 로직
- nullable 변경 필드 반영
- 참조타입(Boolean) -> 원시타입(boolean)으로 변경 *Integer는 그대로 둠
> [FEAT] 온보딩 부모자식 관계 정보 입력(초대하는 측) API  

- src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
- src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/request/TodayAnswerRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
- src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
- src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
closed #19
- 일일문답 페이지에서 질문에 대한 답변을 처리해주는 API 개발
- 상대방에게 푸시알림 나가는 기능은 추후 구현
- JPQL 최적화는 추후에 구현하겠습니다!
> [FEAT] 일일문답 페이지 질문 답변 API

- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/InviteCodeRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/GetInviteCodeResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/InviteResultResponeDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingInviteResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingReceiveResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
- src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetMainViewResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/UserInfoDto.java
- src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
- src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
close #26 
- @JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class) 를 추가해 요청, 응답 json 형식을 스네이크 케이스로 통일
- User 엔티티에 isMeChild 필드를 추가하여 유저가 자식인지의 여부를 저장
- 이에 따른 필드 업데이트 메서드 추가
-  온보딩 과정에서 유저마다 해당 필드 값을 업데이트하는 로직 추가
- Controller 단에서 데이터 불변성을 유지하기 위한 final 키워드 추가
- DTO에서 필요한 형식적 Validation 추가적으로 처리
- 모든 API를 Header의 Access Token에서 유저정보를 꺼내오는 것으로 수정
- 꼼꼼한 예외처리가 필요한 부분이 많이 보였는데 일단 이 부분은 API 명세서 작성 대략 완성해두고 진행하도록 하겠습니다!
> [REFACTOR] 온보딩, 홈 화면 API 리팩토링

- .gitignore
- build.gradle
- src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
- src/main/java/sopt/org/umbbaServer/domain/user/repository/UserRepository.java
- src/main/java/sopt/org/umbbaServer/global/config/FCMConfig.java
- src/main/java/sopt/org/umbbaServer/global/config/ScheduleConfig.java
- src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
- src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/PushRequest.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/FCMController.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMMessage.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMNotificationRequestDto.java
- src/main/resources/application.yaml
close #38 
- 클라이언트 (유저)마다 고유하게 가지는 FCM 토큰으로 요청을 받아 해당 기기로 푸시 메세지를 전송하는 기능을 구현
- 해당 토큰은 처음 요청을 보낼 때 유저의 DB (서버)에 저장해두고 이후 주기적인 알림 전송 등에 사용할 것
- 고정 메세지 템플릿에 대한 enum과 해당 enum에 추가적인 정보를 붙여서 문자열을 생성하기 위해 setter 메서드를 이용함
- 아직 애플에서의 테스트만 완료된 상태라 Android, Apple 각각에 대해 config를 커스텀할 수 있게 주석처리를 해둔 상황
- 우리 서비스의 특성상 부모, 자식 쌍으로 알림 메세지를 전송하는 경우가 많기에, 아직 단일 기기(1:1) 전송으로 구현된 부분을 다수 기기 전송으로 수정할 것 -> 주석처리로 살짝 남아있음
- FCM 관련 서비스 로직을 처리하는 부분이 FCMService, FCMScheduler로 두 군데인데 이를 하나로 합칠 것인지, 아니면 주기적 알람이랑 특정 API 호출 시(ex. 상대 측 답변 완료 알림) 보내는 알람을 구분해둘지? 어떤 게 더 좋을까요
- application.yml의 정리가 아직은 필요한 상황이라 리뷰 후에 수정사항 반영해서 머지하겠습니다!
> [FEAT] FCM 푸시 서버 구축

- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingInviteResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingReceiveResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/dao/ParentchildDao.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
- src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/request/TodayAnswerRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/QnAListResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/qna/model/OnboardingAnswer.java
- src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
- src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/RefreshRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/SocialLoginRequestDto.java
- src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
- src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
closed #43
- DB에 live_together 필드가 남아 있는 것 해결
- 푸시 알림 시간이 "23:00:00" 형식으로 리턴되는 것 "23:00"으로 리턴되게 수정
- YES, NO가 아니라 응, 아니로 선택질문 답변 받도록 수정
- 온보딩 정보 입력 (초대받는 측) API에서 parentchild_id 빠지게 변경
- API 명세서에 수정사항 반영
- snake_case로만 받아지는거 수정
- 과거의 문답 리스트 조회하기 질문이 아니라 주제 보여주는걸로 변경
> [FIX] 온보딩 dto 관련 버그 수정

- src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
- src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetInvitationResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
close #45 
- 메인 홈 관련 API로 로직 분리
- 기존 최근 일일문답 조회 API의 메서드 이동
- Response DTO 추가 생성하여 분리
> [FEAT] 초대장 조회 API로 로직 분리

- src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
- src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
- src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
- src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
closed #52
- 최근 질문과 답변 조회에서도 홈 화면 처럼 index에 대한 정보를 주실 수 있나요? (ex: #1에 사용되는 1)
- 일일 질문 가져올 때 qnaList 끝에 있는거 추가로 X, 필드 추가 따로 해야함
- 스피디 어프로브 부탁드리겠습니다!
> [FEAT] 지금 몇일차 질문에 대해 문답을 나누고 있는지 저장하는 필드 추가

- src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
- src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
#55
- hasAlarm 필드 다시 삭제 (서버에서 보관 필요 없으므로)
- DB에도 반영하였습니다 !
> [FIX] hasAlarm 필드 다시 삭제 (서버에서 보관 필요 없으므로)

- src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
- src/main/java/sopt/org/umbbaServer/domain/qna/dao/QnADao.java
- src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
- src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionSection.java
- src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionType.java
- src/main/java/sopt/org/umbbaServer/domain/qna/repository/QuestionRepository.java
- src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
- src/main/resources/application.yaml
#64
- Q/A 요청사항으로 질문 리스트 보일 때 아직 안쌓인 질문은 안보이도록 처리
- 사용자 맞춤형 질문 제공을 위한 로직 추가
- Enum 타입 수정
- 로직 변경
- 테스트용 API 만들어서 테스트
> [MODIFY] 사용자 맞춤형 질문 제공을 위한 로직 추가

- src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
closed #68
- 상대가 초대장만 수신하고 온보딩 안마쳤는데, 반대측 유저에서 case2가 아니라 1로 출력되는 문제 해결
> [FIX] 초대 받는측이 온보딩을 안끝냈을 때 질문 답변할 수 없도록 변경

- src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
close #77 
- 추가했던 예외 임시로 삭제합니다
- 온보딩한 유저의 부모자식 관계가 이미 존재할 때 발생하는 예외처리 뺐습니다!
> [FIX] 급한 에러사항 수정

- build.gradle
- src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
- src/main/resources/application.yaml
close #88 
- 스케줄링 작업에서 EntityManager를 이용해 수동으로 merge를 한 후, close 하는 부분이 없어 커넥션 풀에 누수가 발생한 것으로 예측됨 
-> 일단 em.close() 를 추가해서 해결
- application.yml에서는 hikari 옵션 추가
아직 스케줄링으로 푸시알림이 제대로 구현되는지 테스트는 안 된 상태입니다 .. 추가적으로 해결하고 다시 이 부분 테스트 해볼게요 !
> [FIX] EntityManager close 추가

- src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
- src/main/java/sopt/org/umbbaServer/global/common/advice/ControllerExceptionAdvice.java
- src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
- src/main/resources/application.yaml
- em.close() 호출 시점을 일단 머지와 커밋 이후 아무데나 넣어뒀는데, 이렇게 하면 트랜잭션이 롤백된 이후에 close가 보장되지 않아서 finally 구문으로 바꿔뒀습니다!
- ControllerAdvice 500에러 핸들링 주석 처리했던 부분 다시 살려뒀습니다
- PostMan Test의 편의를 위해서 소셜 로그인 시 액세스 토큰 로그로 찍어두도록 추가했습니다!
모듈 분리한 버전에도 동일한 내용 반영함요 ~!!
> [FIX] 추가 변경 사항 반영

- umbba-common/src/main/java/sopt/org/umbba/common/exception/ErrorType.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/Parentchild.java
- 간혹 온보딩 끝나는 측에서 버튼을 2번 누르는 바람에 API가 2번 호출되는 경우 오류 발생
- QNA 리스트의 크기가 1+6개가 아닌, 1+6+6개가 되기 때문에 이 부분을 에러 핸들링 하는 것이 필요하다고 판단
- 아라가 매칭 해달라고 해서, 테스트 해보다가 찾은 오류여서 바로 해결합니닷!
> [HOTFIX] API가 중복 호출되어 QNA 리스트가 7개를 넘어가는 오류 해결

- .gitignore
- build.gradle
- umbba-api/src/main/java/sopt/org/umbba/api/controller/user/dto/request/UserInfoDto.java
- umbba-domain/build.gradle
- umbba-domain/src/main/java/sopt/org/umbba/domain/config/jpa/JpaConfig.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/dao/ParentchildDao.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/dao/QnADao.java
- umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
- umbba-notification/src/main/java/sopt/org/umbba/notification/service/scheduler/FCMScheduler.java
close #108 
- Quertdsl을 적용하여 DAO에서 사용했던 jpql 코드를 최적화했습니다
- 의존성 라이브러리 충돌 문제로 정리해둔 내용 노션에 기록해두었으니 참고해주세요!
- 아직 리뷰 확인 후에 지우려고 DAO에서 기존에 사용했던 코드들 주석처리로 남겨두었습니다! 리뷰 달아주신 이후에 지우도록 하겠습니다
- 다음 이슈는 2주.. 내로 해야죠 하핫
> [REFACTOR] Querydsl을 이용한 쿼리 최적화

- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/dao/ParentchildDao.java
closed #113 
하나의 ParentChild에서 나와 연결된 부모 또는 자식을 찾는 쿼리 부분에 오류가 생겼습니다. 
해당 쿼리에서 유저 간 비교 하는 부분을 각각의 객체를 생성해서 비교하는 방식으로 풀어씀으로써 보다 가독성이 높은 코드로 변경했습니다!
> [FIX] Querydsl 코드 관련 에러 해결

- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/dao/ParentchildDao.java
아직 오류가 남아있는 것 같아 일단 기존의 jpql 코드로 돌려놓겠습니다!
> [FIX] jpql 코드로 복구 

- umbba-api/src/main/java/sopt/org/umbba/api/controller/advice/ControllerExceptionAdvice.java
- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/QnAController.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
- umbba-common/src/main/java/sopt/org/umbba/common/exception/ErrorType.java
- umbba-common/src/main/java/sopt/org/umbba/common/exception/SuccessType.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/Parentchild.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/repository/QuestionRepository.java
- umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMController.java
- umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
closed #121
"엄빠도 어렸다"는 더이상 7일에 멈추는 서비스가 아닙니다.
- **지금 현재 DB에 있는 질문들의 타입**
1. 고정 질문 -> 어린시절의 질문 1개
2. 메인 질문 -> 큰 줄기가 되는 질문들 6개
3. 타입 질문 -> 온보딩에서의 답변에 따라서 변경되는 질문 7개
4. 미사용 질문 -> 아직 사용되지 않은 질문 4개 + 12개 더 추가 예정
- **7일 이후에 새롭게 추가될 때 해야하는 작업**
1. 위 4개의 타입 중 메인 질문 + 미사용 질문만 뽑아온다
2. 쭉 뽑아온 질문들 중에서 내가 이미 주고받은 질문은 제한다 (여기까지는 쿼리로 한방에 해결)
3. 이전에 했던 질문과 다른 섹션 질문이 있는지 먼저 찾는다
4. 없다면 동일한 섹션 질문이라도 넣어둔다
6. 그것마저 없다면 멈춘다
- 생각보다 복잡합니다..
- 자세한 내용은 이곳을 참고 -> https://harsh-step-7dd.notion.site/SP3-API-a1bdc3cea2bd4aa4a009490982ecdafc?pvs=4
> [FEAT] 7일 이후 문답 구현

- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/dto/response/MyUserInfoResponseDto.java
closed #128 
- 상대방 미연결 시, 초대코드 팝업에 띄울 `inviteCode` 마이페이지 API response에 추가
간단한 수정사항이라 확인해주시면 바로 머지하겠습니당
> [MODIFY] 마이페이지 API 초대코드 응답 추가

- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/QnAController.java
- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/dto/response/FirstEntryResponseDto.java
- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/dto/response/GetInvitationResponseDto.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/user/AuthService.java
- umbba-common/src/main/java/sopt/org/umbba/common/exception/SuccessType.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/user/User.java
closed #125 
1. 튜토리얼 화면을 띄우기 위한 유저의 **`홈 화면 첫 진입 여부`** 구분
→ 기존에 메인페이지 API 호출했던 부분 전에 **유저의 첫 진입 여부 조회 API를 먼저 호출**하여 튜토리얼을 띄울지에 대한 판단을 수행한다. 
- ❗ **`is_first_entry`** = true 인 경우애 튜토리얼 진행  *나머지는 모두 false
2. 홈 화면 Case `response_case` 추가    
→ 3가지의 response_case로 응답 값을 구분했던 API 에서 4번 케이스와 유저의 첫 질문 답변 작성 여부에 대한 필드가 추가되어, **`response_case = 4`**, **`is_user_first_answer = false`** 인 경우에 따라 첫 질문 답변 작성을 유도한다. 
- 클라&모두에게 공유 : https://www.notion.so/SP3-API-a1bdc3cea2bd4aa4a009490982ecdafc?pvs=4#64a6ed7ea8b34ac4b70b66f6c6b06ed6
- 서버 내부 로직에 대한 공유 : https://www.notion.so/daee7f35dcfb46bf9447277959ddf019?pvs=4
위 링크에 클라이언트의 동작과 내부 구현에 대한 상세한 내용을 적어두었으니 참고해 주시기 바랍니다 :)
- 테스트는 완료했고, 추가로 고려하면 좋을 것 같은 내용이 있다면 자유롭게 의견 주세요 !!
> [MODIFY] 문답 튜토리얼 추가에 따른 API 변경사항 적용

- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/dto/response/TodayQnAResponseDto.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
closed #130 
- SP3 변경사항으로 인해 부모 자식 관계에 1명만 참여하고 있을 때도 오늘의 질문을 알 수 있습니다! (튜토리얼용 첫번째 질문)
- 정확히는 GET /home/case를 호출했을 때 response_case=4인 경우, 튜토리얼과 함께 GET /qna/today 호출이 가능해야 합니다.
(아래 뷰가 나오는 상황)
- 따라서 기존에 GET /qna/today 호출 시 매칭이 완료되지 않았을 경우 에러 핸들링 했던 것을 수정했습니다.
> [FIX] 튜토리얼 오늘의 질문 알 수 있도록 변경

- umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/user/User.java
closed #132
- 현재 한쪽에서 엔딩페이지를 확인한 경우, 다른 측에서 엔딩페이지가 뜨지 않는 오류가 있습니다!
- 이는 현재 답변이 7일차인지 + 둘다 답변을 완료했는지 여부로 판단하고 있기 때문인데요,
- 이 오류를 해결하기 위해 DB에 필드가 추가되어야 함을 파악했습니다.
- 따라서 DB 필드 추가 + 엔딩 페이지 로직 변경이 이루어져야 합니다!
> [FIX] 엔딩 페이지 한쪽에서만 뜨는 오류 수정

- umbba-api/src/main/java/sopt/org/umbba/api/controller/album/AlbumController.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/album/AlbumService.java
- umbba-common/src/main/java/sopt/org/umbba/common/exception/ErrorType.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/album/Album.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/Parentchild.java
closed #138 
Album 추가 등록 시, 최대 허용 가능한 업로드 수를 제한하는 방식으로 변경했습니다.
-> 해당 HTTP Status는 예외처리 편의성을 고려하여 **501 Not Implemented**로 처리했습니다!
Parentchild 테이블에 `isFirstAlbumUpload` , `isDeleteSampleAlbum`라는 필드를 추가하여 분기처리 하고, 아직 한번도 앨범을 등록하지 않은 경우라면, sample 데이터 (id 0번)를 리스트에 담아서 응답하도록 구현했습니다.
- 아직 Example 고정 이미지 URL은 추가해두지 않은 상태입니다.
- 기획 측에 여쭤본 상황이고, 답변 받으면 URL까지 반영해서 올리겠습니다!
> [FEAT] Album  API 추가 기능 구현

- umbba-api/src/main/java/sopt/org/umbba/api/controller/advice/ControllerExceptionAdvice.java
- umbba-api/src/main/java/sopt/org/umbba/api/controller/closer/dto/request/TodayCloserAnswerRequestDto.java
- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/QnAController.java
- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/dto/request/RerollChangeRequestDto.java
- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/dto/response/RerollCheckResponseDto.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/closer/CloserService.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
- umbba-common/src/main/java/sopt/org/umbba/common/exception/ErrorType.java
- umbba-common/src/main/java/sopt/org/umbba/common/exception/SuccessType.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/closer/repository/CloserQuestionRepository.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/Parentchild.java
- umbba-domain/src/main/java/sopt/org/umbba/domain/domain/user/User.java
- umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
closed #123
- 질문 새로고침 로직을 구현하였습니다.
- 질문 새로고침 로직 외의 내용이 꽤 추가되어있는 것 같아 리뷰로 남겨두겠습니다!
> [FEAT] 질문 새로고침 구현 

- README.md
- umbba-api/src/main/java/sopt/org/umbba/api/controller/qna/dto/response/MyUserInfoResponseDto.java
- umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
- 운영서버 v1.1.0의 수정사항을 배포합니다.
https://github.com/Team-Umbba/Umbba-Server/pull/149
- 수정사항이 발생하여 추가로 배포합니다!
> [DEPLOY] 운영서버 v1.1.0 수정사항 배포
